name: Convert and Publish with Pelican


on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Site with Pelican
        run: pelican content -o docs -s publishconf.py

      - name: Create .nojekyll
        run: touch docs/.nojekyll


      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
